### ISSUE TITLE
Combat Toggle

### ISSUE THREAD

**Issue by kennywasafk** [NumyAddon/DialogKey_Numy#1]
First of all thank you very much for picking this up, DialogKey has probably been the only addon that I can't imagine playing the game without and not having an active maintainer resulted in it breaking quite often once Blizzard changed things, leaving it at the discretion of commenters on Curse or in the original github repositories to provide fixes for the rest.

I just wanted to leave this here since I noticed a change in the behaviour of the addon when jumping from pre-DF version to the one posted by ItsNoich. I'm fairly sure that the addon behaved differently in combat, allowing you to use it even when fighting, overriding your keybinds to instead send inputs to the gossip/quest window. Now, while making that behaviour default would probably do more harm than good, having a toggle in the settings window would be really useful in my opinion. 

Anyway, hope this is helpful and that you consider taking some time to add the feature. Thanks again!

**Comment by Numynum** [comment]
while I would 100% love this as well, it's unfortunately been made basically impossible by Blizzard
this is because DialogKey is "catching" key presses before the game looks at keybinds/spells etc, and then depending on the key, and whether there's any frame to show, DKey lets the game handle the key as normal

which is great, and works well
unfortunately, people can use the exact same code to write certain types of bots and other exploitative addons, so blizzard blocked all of that when you're in combat since DF
